USE CUSTOMER_ANALYSIS;

#Q1. WHAT IS THE TOTAL REVENUE GENETRATED BY MALE AND FEMALE CUSTOMER?

SELECT GENDER, SUM(PURCHASE_AMOUNT)
FROM CUSTOMERS
GROUP BY GENDER;

#Q2. WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?

SELECT CUSTOMER_ID,PURCHASE_AMOUNT
FROM CUSTOMERS
WHERE DISCOUNT_APPLIED = 'YES' AND PURCHASE_AMOUNT > (
									SELECT AVG(PURCHASE_AMOUNT)
                                    FROM CUSTOMERS);

#Q3. WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING?

SELECT ITEM_PURCHASED, ROUND(AVG(REVIEW_RATING), 2) AS AVG_REVIEW_RATING
FROM CUSTOMERS
GROUP BY ITEM_PURCHASED
ORDER BY AVG_REVIEW_RATING DESC
LIMIT 5;

#Q4. COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING?

SELECT SHIPPING_TYPE, ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_PURCHASE_AMOUNT
FROM CUSTOMERS
WHERE SHIPPING_TYPE IN ('STANDARD', 'EXPRESS')
GROUP BY SHIPPING_TYPE;

#Q5. DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON-SUBSCRIBERS?

SELECT SUBSCRIPTION_STATUS , COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS , ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_SPEND , ROUND(SUM(PURCHASE_AMOUNT),2) AS TOTAL_REVENUE
FROM CUSTOMERS
GROUP BY SUBSCRIPTION_STATUS;

#Q6. WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNTS APPLIED?

SELECT ITEM_PURCHASED,
       ROUND(SUM(CASE 
                    WHEN DISCOUNT_APPLIED = 'YES' THEN 1 
                    ELSE 0 
                 END) * 100.0 / COUNT(*), 2) AS DISCOUNT_PERCENTAGE
FROM CUSTOMERS
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_PERCENTAGE DESC
LIMIT 5;

#7Q. SEGMENT CUSTOMERS INTO NEW , RETURING , AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES , AND SHOW THE COUNT OF EACH SEGMENT?

WITH CUSTOMER_TYPE AS
(
    SELECT PREVIOUS_PURCHASES,
           CASE 
               WHEN PREVIOUS_PURCHASES = 1 THEN 'NEW'
               WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'RETURNING'
               ELSE 'LOYAL'
           END AS CUSTOMER_SEGMENT
    FROM CUSTOMERS
)

SELECT CUSTOMER_SEGMENT,
       COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT;

#Q8. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY?

WITH ITEM_COUNTS AS
(
    SELECT CATEGORY,
           ITEM_PURCHASED,
           COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
           ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC) AS ITEM_RANK
    FROM CUSTOMERS
    GROUP BY CATEGORY, ITEM_PURCHASED
)

SELECT ITEM_RANK, CATEGORY, ITEM_PURCHASED, TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <= 3;

#Q9. ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?

SELECT SUBSCRIPTION_STATUS , COUNT(CUSTOMER_ID)
FROM CUSTOMERS
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS ;

#10. WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP?

SELECT AGE_GROUP , SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC;
